services:
  tip:
    image: ghcr.io/isaackogan/tls-impersonate-proxy:1
    # build:
    #   context: ..
    #   dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "9090"
    volumes:
      - ../tip.yaml:/etc/tip/tip.yaml:ro
      - tip-ca:/var/lib/tip
    stop_grace_period: 20s
    restart: unless-stopped

volumes:
  tip-ca:
