{{- if and .Values.ca.cert .Values.ca.key (not .Values.ca.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tip.fullname" . }}-ca
  labels: {{- include "tip.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ca.certKey }}: {{ .Values.ca.cert | quote }}
  {{ .Values.ca.keyKey }}: {{ .Values.ca.key | quote }}
{{- end }}
