{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tip.fullname" . }}
  labels: {{- include "tip.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "tip.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: {{ dig "metrics" "path" "/metrics" .Values.config }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
